-- migration: update_missing_name_pl
-- purpose: Add missing Polish translations for all seed products not covered in the previous migration

update public.products
set name_pl = case name_en
  -- Vegetables (Rest)
  when 'Serrano pepper' then 'Papryczka serrano'
  when 'Daikon' then 'Rzodkiew japońska'
  when 'Lotus root' then 'Korzeń lotosu'
  when 'Bamboo shoots' then 'Pędy bambusa'
  when 'Artichoke' then 'Karczoch'
  when 'Okra' then 'Okra'
  when 'Yam' then 'Pochrzyn'
  when 'Cassava' then 'Maniok'
  when 'Taro root' then 'Korzeń taro'
  when 'Jicama' then 'Jicama'
  when 'Chayote' then 'Kolczoch jadalny'
  when 'Spaghetti squash' then 'Dynia makaronowa'
  when 'Acorn squash' then 'Dynia żołędziowa'
  when 'Delicata squash' then 'Dynia delicata'
  when 'Snap peas' then 'Groszek cukrowy'
  when 'Snow peas' then 'Groszek śnieżny'
  when 'Seaweed' then 'Wodorosty'
  when 'Nori' then 'Nori'
  when 'Wakame' then 'Wakame'
  when 'Kombu' then 'Kombu'
  when 'Microgreens' then 'Mikroliście'
  when 'Alfalfa sprouts' then 'Kiełki lucerny'
  when 'Sunflower sprouts' then 'Kiełki słonecznika'
  when 'Pea shoots' then 'Pędy groszku'
  when 'Cress' then 'Rzeżucha'

  -- Dairy
  when 'Whole milk' then 'Mleko pełne'
  when 'Semi-skimmed milk' then 'Mleko półtłuste'
  when 'Skim milk' then 'Mleko odtłuszczone'
  when 'Lactose-free milk' then 'Mleko bez laktozy'
  when 'Goat milk' then 'Mleko kozie'
  when 'Sheep milk' then 'Mleko owcze'
  when 'Evaporated milk' then 'Mleko skondensowane niesłodzone'
  when 'Condensed milk' then 'Mleko skondensowane słodzone'
  when 'Powdered milk' then 'Mleko w proszku'
  when 'Buttermilk' then 'Maślanka'
  when 'Plain yogurt' then 'Jogurt naturalny'
  when 'Greek yogurt' then 'Jogurt grecki'
  when 'Skyr' then 'Skyr'
  when 'Kefir' then 'Kefir'
  when 'Drinkable yogurt' then 'Jogurt pitny'
  when 'Flavored yogurt' then 'Jogurt smakowy'
  when 'Butter' then 'Masło'
  when 'Salted butter' then 'Masło solone'
  when 'Unsalted butter' then 'Masło niesolone'
  when 'Clarified butter' then 'Masło klarowane'
  when 'Ghee' then 'Masło Ghee'
  when 'Heavy cream' then 'Śmietana kremówka'
  when 'Light cream' then 'Śmietana 18%'
  when 'Whipping cream' then 'Śmietana do ubijania'
  when 'Sour cream' then 'Śmietana kwaśna'
  when 'Crème fraîche' then 'Crème fraîche'
  when 'Cream cheese' then 'Serek śmietankowy'
  when 'Cottage cheese' then 'Serek wiejski'
  when 'Ricotta' then 'Ricotta'
  when 'Mascarpone' then 'Mascarpone'
  when 'Mozzarella' then 'Mozzarella'
  when 'Cheddar' then 'Cheddar'
  when 'Gouda' then 'Gouda'
  when 'Edam' then 'Edam'
  when 'Emmental' then 'Ementaler'
  when 'Gruyère' then 'Gruyère'
  when 'Parmesan' then 'Parmezan'
  when 'Pecorino' then 'Pecorino'
  when 'Feta' then 'Feta'
  when 'Halloumi' then 'Halloumi'
  when 'Brie' then 'Brie'
  when 'Camembert' then 'Camembert'
  when 'Blue cheese' then 'Ser z niebieską pleśnią'
  when 'Gorgonzola' then 'Gorgonzola'
  when 'Roquefort' then 'Roquefort'
  when 'Processed cheese' then 'Ser topiony'
  when 'Cheese spread' then 'Serek do smarowania'
  when 'Ice cream' then 'Lody'
  when 'Gelato' then 'Gelato'
  when 'Frozen yogurt' then 'Mrożony jogurt'
  when 'Milkshake' then 'Shake mleczny'
  when 'Custard' then 'Budyń'
  when 'Pudding' then 'Pudding'
  when 'Whey' then 'Serwatka'
  when 'Casein' then 'Kazeina'
  when 'Dulce de leche' then 'Kajmak'
  when 'Quark' then 'Twaróg'
  when 'Farmer cheese' then 'Ser farmerski'
  when 'Paneer' then 'Paneer'
  when 'Labneh' then 'Labneh'
  when 'Clotted cream' then 'Krem clotted'

  -- Legumes
  when 'Chickpeas' then 'Ciecierzyca'
  when 'Black chickpeas' then 'Czarna ciecierzyca'
  when 'Lentils' then 'Soczewica'
  when 'Red lentils' then 'Czerwona soczewica'
  when 'Black beans' then 'Czarna fasola'
  when 'Kidney beans' then 'Fasola czerwona Kidney'
  when 'Pinto beans' then 'Fasola pinto'
  when 'White beans' then 'Fasola biała'
  when 'Navy beans' then 'Fasola navy'
  when 'Cannellini beans' then 'Fasola cannellini'
  when 'Great northern beans' then 'Fasola jaś karłowy'
  when 'Red beans' then 'Fasola czerwona'
  when 'Adzuki beans' then 'Fasola adzuki'
  when 'Mung beans' then 'Fasola mung'
  when 'Black-eyed peas' then 'Fasola czarne oczko'
  when 'Soybeans' then 'Soja'
  when 'Edamame' then 'Edamame'
  when 'Peas' then 'Groszek'
  when 'Split peas' then 'Groch łuskany'
  when 'Broad beans' then 'Bób'
  when 'Fava beans' then 'Bób drobny'
  when 'Lupin beans' then 'Łubin'
  when 'Hyacinth beans' then 'Wspięga'
  when 'Winged beans' then 'Głąbiel'
  when 'Cowpeas' then 'Wspięga chińska'
  when 'Pigeon peas' then 'Nikla indyjska'
  when 'Cranberry beans' then 'Fasola borlotti'
  when 'Lima beans' then 'Fasola lima'
  when 'Horse gram' then 'Złotokap'
  when 'Bambara groundnuts' then 'Orzechy bambary'
  when 'Peanuts' then 'Orzeszki ziemne'
  when 'Bean sprouts' then 'Kiełki fasoli'
  when 'Mung bean sprouts' then 'Kiełki fasoli mung'

  -- Grains
  when 'White rice' then 'Ryż biały'
  when 'Brown rice' then 'Ryż brązowy'
  when 'Basmati rice' then 'Ryż basmati'
  when 'Jasmine rice' then 'Ryż jaśminowy'
  when 'Wild rice' then 'Dziki ryż'
  when 'Black rice' then 'Ryż czarny'
  when 'Red rice' then 'Ryż czerwony'
  when 'Arborio rice' then 'Ryż arborio'
  when 'Sushi rice' then 'Ryż do sushi'
  when 'Oats' then 'Płatki owsiane'
  when 'Steel cut oats' then 'Płatki owsiane cięte'
  when 'Oat bran' then 'Otręby owsiane'
  when 'Wheat' then 'Pszenica'
  when 'Whole wheat' then 'Pszenica pełnoziarnista'
  when 'Bulgur' then 'Kasza bulgur'
  when 'Couscous' then 'Kuskus'
  when 'Semolina' then 'Semolina'
  when 'Farro' then 'Farro'
  when 'Spelt' then 'Orkisz'
  when 'Kamut' then 'Kamut'
  when 'Barley' then 'Jęczmień'
  when 'Rye' then 'Żyto'
  when 'Corn' then 'Kukurydza'
  when 'Popcorn' then 'Popcorn'
  when 'Polenta' then 'Polenta'
  when 'Cornmeal' then 'Mąka kukurydziana'
  when 'Grits' then 'Kasza kukurydziana grits'
  when 'Millet' then 'Proso'
  when 'Sorghum' then 'Sorgo'
  when 'Teff' then 'Teff'
  when 'Quinoa' then 'Komosa ryżowa'
  when 'White quinoa' then 'Biała komosa ryżowa'
  when 'Red quinoa' then 'Czerwona komosa ryżowa'
  when 'Buckwheat' then 'Gryka'
  when 'Buckwheat groats' then 'Kasza gryczana'
  when 'Amaranth' then 'Amarantus'
  when 'Freekeh' then 'Freekeh'
  when 'Triticale' then 'Pszenżyto'
  when 'Fonio' then 'Fonio'
  when 'Rice noodles' then 'Makaron ryżowy'
  when 'Egg noodles' then 'Makaron jajeczny'
  when 'Udon noodles' then 'Makaron udon'
  when 'Soba noodles' then 'Makaron soba'
  when 'Pasta' then 'Makaron'
  when 'Whole wheat pasta' then 'Makaron pełnoziarnisty'
  when 'Spaghetti' then 'Spaghetti'
  when 'Penne' then 'Penne'
  when 'Fusilli' then 'Świderki'
  when 'Macaroni' then 'Makaron rurki'
  when 'Lasagna sheets' then 'Płaty lasagne'
  when 'White bread' then 'Chleb pszenny'
  when 'Whole wheat bread' then 'Chleb pełnoziarnisty'
  when 'Rye bread' then 'Chleb żytni'
  when 'Sourdough bread' then 'Chleb na zakwasie'
  when 'Multigrain bread' then 'Chleb wieloziarnisty'
  when 'Bagel' then 'Bajgiel'
  when 'English muffin' then 'Muffin angielski'
  when 'Wheat tortilla' then 'Tortilla pszenna'
  when 'Corn tortilla' then 'Tortilla kukurydziana'
  when 'Whole grain crackers' then 'Krakersy pełnoziarniste'
  when 'Muesli' then 'Musli'
  when 'Granola' then 'Granola'
  when 'Bran flakes' then 'Płatki kukurydziane z otrębami'
  when 'Corn flakes' then 'Płatki kukurydziane'
  when 'Rice cakes' then 'Wafle ryżowe'
  when 'Puffed rice' then 'Ryż preparowany'
  when 'Puffed wheat' then 'Pszenica preparowana'

  -- Meat
  when 'Whole chicken' then 'Cały kurczak'
  when 'Chicken breast' then 'Pierś z kurczaka'
  when 'Chicken thighs' then 'Udo z kurczaka'
  when 'Chicken drumsticks' then 'Podudzie z kurczaka'
  when 'Chicken wings' then 'Skrzydełka z kurczaka'
  when 'Ground chicken' then 'Mielone mięso z kurczaka'
  when 'Chicken liver' then 'Wątróbka drobiowa'
  when 'Chicken gizzards' then 'Żołądki drobiowe'
  when 'Whole turkey' then 'Cały indyk'
  when 'Turkey breast' then 'Pierś z indyka'
  when 'Turkey thighs' then 'Udo z indyka'
  when 'Ground turkey' then 'Mielone mięso z indyka'
  when 'Turkey wings' then 'Skrzydełka z indyka'
  when 'Ground beef' then 'Mięso mielone wołowe'
  when 'Beef sirloin steak' then 'Stek z polędwicy wołowej'
  when 'Beef tenderloin steak' then 'Stek z polędwiczki wołowej'
  when 'Beef ribeye steak' then 'Stek z antrykotu'
  when 'Beef T-bone steak' then 'Stek T-bone'
  when 'Beef porterhouse steak' then 'Stek Porterhouse'
  when 'Beef flank steak' then 'Stek z łaty'
  when 'Beef skirt steak' then 'Stek skirt'
  when 'Beef chuck roast' then 'Karkówka wołowa'
  when 'Beef brisket' then 'Mostek wołowy'
  when 'Beef short ribs' then 'Żeberka wołowe'
  when 'Beef shank' then 'Gicz wołowa'
  when 'Beef liver' then 'Wątroba wołowa'
  when 'Beef heart' then 'Serce wołowe'
  when 'Beef tongue' then 'Ozór wołowy'
  when 'Pork chops' then 'Kotlety schabowe'
  when 'Pork loin' then 'Schab'
  when 'Pork tenderloin' then 'Polędwiczka wieprzowa'
  when 'Pork shoulder' then 'Łopatka wieprzowa'
  when 'Pork ribs' then 'Żeberka wieprzowe'
  when 'Ground pork' then 'Mięso mielone wieprzowe'
  when 'Pork belly' then 'Boczek'
  when 'Ham' then 'Szynka'
  when 'Bacon' then 'Boczek wędzony'
  when 'Pork sausage' then 'Kiełbasa wieprzowa'
  when 'Pork liver' then 'Wątroba wieprzowa'
  when 'Lamb chops' then 'Kotlety jagnięce'
  when 'Ground lamb' then 'Mielona jagnięcina'
  when 'Lamb leg' then 'Udziec jagnięcy'
  when 'Lamb shoulder' then 'Łopatka jagnięca'
  when 'Lamb shank' then 'Gicz jagnięca'
  when 'Rack of lamb' then 'Comber jagnięcy'
  when 'Lamb liver' then 'Wątroba jagnięca'
  when 'Veal cutlet' then 'Sznycel cielęcy'
  when 'Veal loin' then 'Schab cielęcy'
  when 'Veal shank' then 'Gicz cielęca'
  when 'Ground veal' then 'Mielona cielęcina'
  when 'Whole duck' then 'Kaczka w całości'
  when 'Duck breast' then 'Pierś z kaczki'
  when 'Duck legs' then 'Nogi z kaczki'
  when 'Goose' then 'Gęś'
  when 'Goose breast' then 'Pierś z gęsi'
  when 'Rabbit meat' then 'Mięso królika'
  when 'Venison' then 'Sarnina'
  when 'Bison' then 'Mięso bizona'
  when 'Elk meat' then 'Mięso z łosia'
  when 'Wild boar' then 'Mięso z dzika'
  when 'Salami' then 'Salami'
  when 'Pepperoni' then 'Pepperoni'
  when 'Prosciutto' then 'Prosciutto'
  when 'Chorizo' then 'Chorizo'
  when 'Hot dog' then 'Parówka'
  when 'Beef sausage' then 'Kiełbasa wołowa'
  when 'Turkey sausage' then 'Kiełbasa z indyka'
  when 'Liver' then 'Wątróbka'
  when 'Kidney' then 'Nerka'
  when 'Heart' then 'Serce'
  when 'Tongue' then 'Ozór'
  when 'Tripe' then 'Flaki'

  -- Fish
  when 'Salmon' then 'Łosoś'
  when 'Atlantic salmon' then 'Łosoś atlantycki'
  when 'Sockeye salmon' then 'Łosoś nerka'
  when 'Smoked salmon' then 'Łosoś wędzony'
  when 'Tuna' then 'Tuńczyk'
  when 'Yellowfin tuna' then 'Tuńczyk żółtopłetwy'
  when 'Bluefin tuna' then 'Tuńczyk błękitnopłetwy'
  when 'Cod' then 'Dorsz'
  when 'Pacific cod' then 'Dorsz pacyficzny'
  when 'Halibut' then 'Halibut'
  when 'Sole' then 'Sola'
  when 'Tilapia' then 'Tilapia'
  when 'Catfish' then 'Sum'
  when 'Mackerel' then 'Makrela'
  when 'Herring' then 'Śledź'
  when 'Sardine' then 'Sardynka'
  when 'Anchovy' then 'Sardela'
  when 'Eel' then 'Węgorz'
  when 'Trout' then 'Pstrąg'
  when 'Rainbow trout' then 'Pstrąg tęczowy'
  when 'Sea bass' then 'Okoń morski'
  when 'Snapper' then 'Lucjan czerwony'
  when 'Grouper' then 'Granik'
  when 'Mahi mahi' then 'Koryfena'
  when 'Swordfish' then 'Miecznik'
  when 'Turbot' then 'Skarp'
  when 'Plaice' then 'Gładzica'
  when 'Carp' then 'Karp'
  when 'Pike' then 'Szczupak'
  when 'Perch' then 'Okoń'
  when 'Zander' then 'Sandacz'
  when 'Shrimp' then 'Krewetki małe'
  when 'Prawn' then 'Krewetki królewskie'
  when 'Crab' then 'Krab'
  when 'Lobster' then 'Homar'
  when 'Crayfish' then 'Rak'
  when 'Mussels' then 'Małże'
  when 'Clams' then 'Małże miękkie'
  when 'Oysters' then 'Ostrygi'
  when 'Scallops' then 'Przegrzebki'
  when 'Squid' then 'Kalmary'
  when 'Octopus' then 'Ośmiornica'
  when 'Cuttlefish' then 'Mątwa'
  when 'Caviar' then 'Kawior'
  when 'Fish roe' then 'Ikra rybia'
  when 'Fish sticks' then 'Paluszki rybne'
  when 'Smoked mackerel' then 'Makrela wędzona'
  when 'Pickled herring' then 'Śledź marynowany'
  when 'Salmon sashimi' then 'Sashimi z łososia'
  when 'Tuna sashimi' then 'Sashimi z tuńczyka'
  when 'Mixed seafood' then 'Mieszanka owoców morza'

  else name_pl
end;
